
"""
window_pair_builder.py

Purpose
-------
Build corresponding AVHRR-MODIS window pairs.

Assumptions
-----------
1. AVHRR and MODIS are already on the same pixel grid.
2. Same shape.
3. Same GeoTransform.
4. Same pixel size.

Since preprocessing guarantees identical grids,
the corresponding MODIS window has the SAME
row/column coordinates as the AVHRR window.

Author : Bhaskar
"""

from osgeo import gdal
import numpy as np


def read_images(avhrr_file,
                modis_file,
                debug=True):
    """
    Read AVHRR and MODIS images.

    Returns
    -------
    avhrr_image
    modis_image
    """

    if debug:
        print("\n========== Reading Images ==========")

    avhrr_ds = gdal.Open(avhrr_file)
    modis_ds = gdal.Open(modis_file)

    if avhrr_ds is None:
        raise RuntimeError("Cannot open AVHRR image.")

    if modis_ds is None:
        raise RuntimeError("Cannot open MODIS image.")

    avhrr = avhrr_ds.GetRasterBand(1).ReadAsArray()
    modis = modis_ds.GetRasterBand(1).ReadAsArray()

    if debug:

        print("AVHRR Shape :", avhrr.shape)
        print("MODIS Shape :", modis.shape)

    return avhrr, modis


def build_window_pairs(windows,
                       avhrr_image,
                       modis_image,
                       debug=True):
    """
    Build corresponding AVHRR-MODIS window pairs.

    Parameters
    ----------
    windows : list
        Generated by generate_windows()

    avhrr_image : ndarray

    modis_image : ndarray

    Returns
    -------
    list
    """

    if debug:
        print("\n========== Building Window Pairs ==========")

    pairs = []

    for window in windows:

        avhrr_window = avhrr_image[
            window.row_start:window.row_end,
            window.col_start:window.col_end
        ]

        modis_window = modis_image[
            window.row_start:window.row_end,
            window.col_start:window.col_end
        ]

        pairs.append({

            "window_id": window.id,

            "row_start": window.row_start,
            "row_end": window.row_end,

            "col_start": window.col_start,
            "col_end": window.col_end,

            "center_row": window.center_row,
            "center_col": window.center_col,

            "avhrr_window": avhrr_window,

            "modis_window": modis_window

        })

    if debug:

        print("Total Window Pairs :", len(pairs))

    return pairs
